/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UzyNative */

#ifndef _Included_UzyNative
#define _Included_UzyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UzyNative
 * Method:    processDirect
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_UzyNative_processDirect
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
